export const TodoActions = {
  ADD_TODO: 'ADD_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  TOGGLE_STATUS: 'TOGGLE_STATUS',
  UPDATE_TODO: 'UPDATE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  RESET_EDIT_TODO: 'RESET_EDIT_TODO',
}